name: Testing latest pushed commits

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    name: Test and build debug APK

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Upload APK to workspace
        uses: actions/upload-artifact@v2
        with:
          name: latestApk
          path: app/build/outputs/apk/debug/app-debug.apk